# Generated by Django 4.1.6 on 2023-02-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('descr', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(height_field=700, max_length=700, upload_to='file/itemimages', width_field=700)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='auctions.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='auctions.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('listing', models.ManyToManyField(blank=True, related_name='bids', to='auctions.listings')),
            ],
        ),
    ]
