# Generated by Django 4.1.6 on 2023-02-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default=None, upload_to='images/items'),
        ),
    ]
