# Generated by Django 4.1.6 on 2023-02-04 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_comment_comments_comment_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('descr', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('userlist', models.ManyToManyField(blank=True, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('descr', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('createdlist', models.ManyToManyField(blank=True, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
