# Generated by Django 4.1.6 on 2023-02-04 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist_createditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='userlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='createdlist',
            field=models.ManyToManyField(blank=True, related_name='createditem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishitem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CreatedItem',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
