# Generated by Django 4.1.6 on 2023-02-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='descr',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
