# Generated by Django 4.1.6 on 2023-02-05 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='userbid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wagers', to=settings.AUTH_USER_MODEL),
        ),
    ]
