# Generated by Django 4.1.6 on 2023-02-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_winner_alter_listing_maxbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='maxbid',
            field=models.IntegerField(default=0),
        ),
    ]
