# Generated by Django 4.1.6 on 2023-02-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_maxbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='maxbid',
        ),
    ]
