# Generated by Django 4.1.6 on 2023-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_listing_maxbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
        migrations.AddField(
            model_name='listing',
            name='winningbid',
            field=models.IntegerField(default=None),
        ),
    ]
